### PR TITLE
update kotlin to 1.5.31 and gradle to 7.4 and ktfmt to 0.32

### PR DESCRIPTION
**Pull request by GoldSubmarine**
## 🚀 Description

update kotlin to 1.5.31 and gradle to 7.4 and ktfmt to 0.32

### CODE REVIEW

**Review by cortinico — APPROVED** [review]

**Comment by cortinico** [comment]
Please update the PR description if this is green 👍

**Comment by cortinico** [comment]
Are you still working on this @GoldSubmarine or should I take over?

**Comment by GoldSubmarine** [comment]
Please take over it. I can compile it locally, but it fails in CI.

> 'compileJava' task (current target is 11) and 'compileKotlin' task (current target is 1.8) jvm target compatibility should be set to the same Java version.

It seems to be caused by a different compiled target version, but I don't know how to solve it.

**Comment by cortinico** [comment]
I've cherry picked the first commit of your PR here #53

**Pull request closed without merging**
