### PR TITLE
Fix task descriptions

### LINKED ISSUE #340: Task descriptions are incorrect
The descriptions of `ktfmtFormat...` and `ktfmtCheck...` tasks are incorrect, I think they were just mixed up.

## Current behaviour

__Check Task:__
https://github.com/cortinico/ktfmt-gradle/blob/0d43625fa8988de6309b38fef7fdaead62c03978/plugin-build/plugin/src/main/java/com/ncorti/ktfmt/gradle/KtfmtPluginUtils.kt#L83 

__Format Task:__
https://github.com/cortinico/ktfmt-gradle/blob/0d43625fa8988de6309b38fef7fdaead62c03978/plugin-build/plugin/src/main/java/com/ncorti/ktfmt/gradle/KtfmtPluginUtils.kt#L110

### PR DESCRIPTION
**Pull request by jessestricker**
## 🚀 Description

I've just switched the task descriptions.

## 📄 Motivation and Context

Fixes #340.

## 🧪 How Has This Been Tested?

No tests needed, I hope 😅. 

## 📦 Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## ✅ Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by simonhauck** [comment]
Hehehhe :D 
I think we had the same idea: https://github.com/cortinico/ktfmt-gradle/pull/341

**Review by simonhauck — CHANGES_REQUESTED** [review]
If you create also a changelog entry similar to this here
https://github.com/cortinico/ktfmt-gradle/pull/341/files
I can approve your PR and merge it.

**Comment by jessestricker** [comment]
The online GitHub editor changed the final newline in the CHANGELOG.md, is that an issue?

**Comment by simonhauck** [comment]
> The online GitHub editor changed the final newline in the CHANGELOG.md, is that an issue?

Personally, I do not mind, but I am not sure if @cortinico has some opinion about this. Just to be safe, I remove the new line.

**Review by simonhauck — APPROVED** [review]

**Comment by simonhauck** [comment]
@jessestricker Thanks your Bug report and also the quick PR :) This is really appreciated.

**Pull request merged**
